# https://github.com/prestodb/presto/blob/master/.travis.yml
language: java
env:
  global:
    - MAVEN_OPTS="-Xmx512M -XX:+ExitOnOutOfMemoryError"
    - MAVEN_SKIP_CHECKS_AND_DOCS="-Dair.check.skip-all=true -Dmaven.javadoc.skip=true"
sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.m2/repository

install:
  - ./mvnw -v

script:
  - ./mvnw install -DskipTests -B -T C1 -P ci $MAVEN_SKIP_CHECKS_AND_DOCS

before_cache:
  # Make the cache stable between builds by removing build output
  - rm -rf $HOME/.m2/repository/com/facebook

notifications:
  webhooks:
    - https://devhose.spt-engprod-pro.schibsted.io/devhose/travis

before_deploy:
  - mkdir /tmp/artifacts
  - cp -n presto-server/target/presto-server-*.tar.gz /tmp/artifacts
  - ls -lah /tmp/artifacts

deploy:
  on:
    all_branches: all
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh

